// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUI9AjSZ8Qu1KI8RYuKhUmfmKuhG-4Xw4',
    appId: '1:699455540180:web:183f3e06eaef7f681d6441',
    messagingSenderId: '699455540180',
    projectId: 'mr-ca-virtuals',
    authDomain: 'mr-ca-virtuals.firebaseapp.com',
    storageBucket: 'mr-ca-virtuals.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZZsCgU0hTXQUGBjBtswjigB4uUnIAB0',
    appId: '1:699455540180:android:b669a1a6fe2a2c2a1d6441',
    messagingSenderId: '699455540180',
    projectId: 'mr-ca-virtuals',
    storageBucket: 'mr-ca-virtuals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PDX3XIqwbs2CUEkBXq-oq9qwmbrmgCc',
    appId: '1:699455540180:ios:e1f613f9f6a17dec1d6441',
    messagingSenderId: '699455540180',
    projectId: 'mr-ca-virtuals',
    storageBucket: 'mr-ca-virtuals.firebasestorage.app',
    androidClientId: '699455540180-052bfg5l7qq9immjmbgarotr6g4bf196.apps.googleusercontent.com',
    iosClientId: '699455540180-uj7pjd20e8mcn5529b3nu5fdr4ao7qai.apps.googleusercontent.com',
    iosBundleId: 'com.kirubakaran.mrcavirtualsadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUI9AjSZ8Qu1KI8RYuKhUmfmKuhG-4Xw4',
    appId: '1:699455540180:web:e497c62df621a2ed1d6441',
    messagingSenderId: '699455540180',
    projectId: 'mr-ca-virtuals',
    authDomain: 'mr-ca-virtuals.firebaseapp.com',
    storageBucket: 'mr-ca-virtuals.firebasestorage.app',
  );
}
